### ISSUE TITLE
Library symbols should be hidden by default

### ISSUE THREAD

**Issue by azeey** [gazebosim/gz-cmake#166]
## Environment
* OS Version: Ubuntu 18.04
* Source or binary build? source, ign-cmake2 (17b7058ff5c9de2f6f396d1a000dd0366481d621)

## Description
* Expected behavior: Symbols are hidden by default as stated in https://github.com/ignitionrobotics/ign-cmake/blob/17b7058ff5c9de2f6f396d1a000dd0366481d621/cmake/Export.hh.in#L45-L52
* Actual behavior: Symbols without the `*_HIDDEN` macro are visible

## Steps to reproduce
Here's an MWE: https://github.com/azeey/sandbox/tree/master/ign-cmake-visibility

After building, use `nm -C lib/libtset_ign_cmake_visibility.so | grep test_` to see which symbols are hidden:

```
 nm -C lib/libtest_ign_cmake_visibility.so | grep test_
00000000000005c0 T test_hidden_func(int, int)
00000000000005e0 T test_visible_func(int, int)
00000000000005d0 t test_explicitly_hidden_func(int, int)
```

`test_hidden_func` should be hidden by default, but as the `T` (global symbol) in the `nm` output shows, it is visibile.

**Comment by scpeters** [comment]
keep open until we change the default behavior in ignition-cmake3

**Comment by scpeters** [comment]
I guess we forgot to reconfigure the default behavior in gz-cmake3

**Comment by j-rivero** [comment]
> I guess we forgot to reconfigure the default behavior in gz-cmake3

Unfortunately we lost the moment to get the changes done. I've renamed the label to gz-cmake4. I've a testing workspace ready for testing but last time it was broken on gz-math7 with was quite early in the dependency chain. We probably want to fix the issues before committing the change to gz-cmake to avoid broken compilations on gz family.

**Comment by j-rivero** [comment]
As suggested by @azeey  and @scpeters  in https://github.com/gazebosim/gz-math/pull/566#issuecomment-1793258765. Best way to test CI could be:

 * Pass HIDE_SYMBOLS_BY_DEFAULT to the gz_configure_build calls in every gz-* package
 * Test and verify that CI / nightly builds are happy
 * Remove HIDE_SYMBOLS_BY_DEFAULT from the gz_configure_build calls in every gz-* package
 * Merge  https://github.com/gazebosim/gz-cmake/pull/392

**Comment by j-rivero** [comment]
> As suggested by @azeey and @scpeters in [gazebosim/gz-math#566 (comment)](https://github.com/gazebosim/gz-math/pull/566#issuecomment-1793258765). Best way to test CI could be:
> 
>     * Pass HIDE_SYMBOLS_BY_DEFAULT to the gz_configure_build calls in every gz-* package
> 
>     * Test and verify that CI / nightly builds are happy
> 

All until here is now done.

>     * Remove HIDE_SYMBOLS_BY_DEFAULT from the gz_configure_build calls in every gz-*    * Merge

As pointed by @scpeters we are here. Let's remove the added symbols from all libs.
