### ISSUE TITLE
FindIgnOGRE2: how to find a from-source (non-system) install?

### ISSUE THREAD

**Issue by peci1** [gazebosim/gz-cmake#192]
## Environment
* OS Version: Ubuntu 18.04
* Source or binary build? Source 3971db877d5aca

## Description
* Expected behavior: FindIgnOGRE2 finds local source build of OGRE2 if it is in `CMAKE_PREFIX_PATH`
* Actual behavior: It finds the system-installed one.

I have OGRE2 source build in a colcon workspace together with ign-rendering4. I don't see a way to point `FindIgnOGRE2` to this source build. In the CMake module, first a check for `OGRE-2.1` is done, and if found, the rest of the search logic is skipped. And as the comment correctly points out, `OGRE-2.1` is the name of the system-installed binary library, whereas source libraries use just `OGRE`. So once there is an `OGRE-2.1` installed in the system, the CMake module doesn't allow me to point it anywhere else...

**Comment by mjcarroll** [comment]
There isn't a consistent way to do it at the moment.  We do all of the name mangling via the Debian packaging step, so it's not reflected in the CMake.

In the past, @ahcorde and I hardcoded paths to be able to use the colcon-local version, but I don't know if that is current best practice.

**Comment by traversaro** [comment]
Just to crossref the related issues, eventually this problem will be solved upstream by https://github.com/OGRECave/ogre-next/issues/232 .

**Comment by peci1** [comment]
Ok, good to hear there is activity to solve it upstream ;)

**Comment by iche033** [comment]
https://github.com/gazebosim/gz-cmake/pull/342 makes it work with ogre 2.3 from our fork: https://github.com/gazebo-forks/ogre-next/tree/gazebo/v2-3 in a colcon workspace. 

ogre-next needs to be built with these variables: https://github.com/gazebo-forks/ogre-next/blob/gazebo/v2-3/colcon.pkg

**Comment by azeey** [comment]
Closing since it's fixed by #342.
