### ISSUE TITLE
Roadmap to ign-cmake3/gz-cmake3

### ISSUE THREAD

**Issue by j-rivero** [gazebosim/gz-cmake#227]
ign-cmake project has stay in the 2.x series for some time now without the need of bumping the major version. The idea is to keep as it is but some intrusive changes have appeared over time that could require a major bump not to affect current behavior without providing the right migration mechanism.

I have created the [`gz-cmake3`](https://github.com/ignitionrobotics/ign-cmake/labels/%3Aarrow_up_small%3A%20%20gz-cmake3) label to mark them.

**Comment by j-rivero** [comment]
Python deprecation cycle is pending https://github.com/ignitionrobotics/ign-cmake/pull/226/files#diff-bffd79b6dfc0249788161fb5a9599927b0826d60146bff83e6400b6f5c8059c3R41-R45

**Comment by j-rivero** [comment]
When gz software is transitioned to ign-cmake3 we need to revert the workaround in gazebodistro, see https://github.com/ignition-tooling/gazebodistro/pull/91/files#r849023064

**Comment by azeey** [comment]
Can this issue be closed?
