### ISSUE TITLE
Support for specifying components of FindPython3 in IgnPython

### ISSUE THREAD

**Issue by Bi0T1N** [gazebosim/gz-cmake#269]
## Desired behavior
It should be possible to have a macro that allows to specify what exactly should be searched for by the CMake command of `FindPython3`. Right now it supports `Interpreter`, `Compiler`, `Development` and `NumPy` which might be helpful in some cases or are required for specific modules.  
A possible use-case is `pybind11` as noted in https://github.com/gazebosim/gz-math/pull/402 because it requires some components.

## Additional context
- https://cmake.org/cmake/help/latest/module/FindPython3.html
- https://github.com/gazebosim/gz-cmake/issues/215

**Comment by scpeters** [comment]
we have deprecated `GzPython` in favor of calling `find_package(Python3)` directly, so users should specify their own components
