### ISSUE TITLE
Branch coverage results hard to interpret

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-cmake#28]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/issues/28)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
Our test coverage is harder to interpret since we merged branch coverage support in [pull request #46](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/pull-requests/46). Previously, line of code would be marked green (covered) or red (uncovered). Now there are many lines marked yellow, and it is not clear to me why that is the case. Some of the yellow lines (like [ignition/math/Filter.hh:92](https://codecov.io/bb/ignitionrobotics/ign-math/src/default/include/ignition/math/Filter.hh#L92) or [ign-math/src/SignalStat.cc:67](https://codecov.io/bb/ignitionrobotics/ign-math/src/default/src/SignalStats.cc#L67)) don't appear to have any branching at all.

Does anyone else know how to interpret these?

**Comment by azeey** [comment]
@scpeters Can this be closed since https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/pull-requests/66/page/1 has been merged?

**Comment by scpeters** [comment]
yes!
