### ISSUE TITLE
libignition-math6-dev on Jammy requires libignition-cmake2-dev 2.13.0 which is unavailable

### ISSUE THREAD

**Issue by vatanaksoytezer** [gazebosim/gz-cmake#304]
## Environment
* OS Version: 22.04
* Source or binary build: Binary - 2.12.1

## Description
* Expected behavior: libignition-math6-dev on Jammy requires libignition-cmake2-dev 2.13.0 which is unavailable. The latest available version on Jammy of this package is 2.12.1 which causes all our CI and docker jobs to fail at `apt install ros-&{ROS_DISTRO}-rviz2` step.
* Actual behavior: Releasing 2.13.0 to Jammy should fix this.

## Steps to reproduce
- Related issue here: https://github.com/ros-planning/moveit2/issues/1520
- An example CI run is here: https://github.com/ros-planning/moveit2/runs/7859848455?check_suite_focus=true
- Build the following dockerfile: https://github.com/ros-planning/moveit2/blob/main/.docker/release/Dockerfile

## Output
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libignition-math6-dev : Depends: libignition-cmake2-dev (>= 2.13.0) but 2.12.1-2~jammy is to be installed
E: Unable to correct problems, you have held broken packages.
ERROR: the following rosdeps failed to install
  apt: command [apt-get install -y ros-rolling-rviz2] failed
  ```

**Comment by vatanaksoytezer** [comment]
Friendly ping to @mjcarroll and @chapulina as this seems critical for other ROS folks as well.

**Comment by mjcarroll** [comment]
Thanks for reporting, we are looking into it.

**Comment by chapulina** [comment]
The issue was introduced here:

* https://github.com/ros-infrastructure/reprepro-updater/pull/160

It's being fixed here:

* https://github.com/ros-infrastructure/reprepro-updater/pull/165

**Comment by benhadad** [comment]
why does this problem come back? Thought it was fixed. what would cause this problem to keep replicating? A bad responsitory?

**Comment by mxgrey** [comment]
I've experienced a similar error after updating to 22.04 and forgetting to update my apt repos. Maybe try running
```
$ grep -rn gazebo /etc/apt/sources.list.d/
```
and see if any bad/old gazebo repos show up. If they do then deleting those files may fix your problem.

**Comment by j-rivero** [comment]
> why does this problem come back? Thought it was fixed. what would cause this problem to keep replicating? A bad responsitory?

Can you provide reproducible steps to trigger the problem?
