### ISSUE TITLE
packages using ign-cmake1 aren't exporting packages using ign-cmake0 in pkg-config requires

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-cmake#35]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/issues/35)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
This is a variant of the bug fixed in [pull request #56](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/pull-requests/56), for which a test was added in [pull request #58](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/pull-requests/58). In the original, a package `core_child` that depends on `core_no_deps` wasn't exporting this dependency information in the pkg-config file. This bug is a variant in which `core01_child` uses `ign-cmake1`, while the dependency `core01_no_deps` uses `ign-cmake0`. In this case, `core01_child` is not exporting its dependency on `core01_no_deps` in the .pc file. I've made an example to illustrate this in [branch requires_01](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/branch/requires01_test), though I'm not sure if we will merge it to default, since it requires ignition-cmake0. It is helpful though in illustrating the problem and testing fixes.

**Comment by azeey** [comment]
Closing since `ign-cmake0` and `ign-cmake1` are both EOL.
