### ISSUE TITLE
Use cmake 3.22.1 features in Ionic

### ISSUE THREAD

**Issue by scpeters** [gazebosim/gz-cmake#350]
## Desired behavior

The next major release of gz-cmake will be supported on newer distributions with newer versions of cmake than version 3.10.2 that is currently used in gz-cmake3. We should identify which version of cmake we can target in order to use those new features.

## Alternatives considered

Continue using cmake 3.10.2.

## Implementation suggestion

Look into updating the following places where it is suggested that a new version of cmake will allow changes:

* [ ] won't fix ~~[GzFindPackage.cmake:286-328](https://github.com/gazebosim/gz-cmake/blob/e9a97b1214b920b17983ab358e790f2dc631e8d7/cmake/GzFindPackage.cmake#L286-L328)~~
* [x] Find python directly in downstream packages so that [GzPython.cmake](https://github.com/gazebosim/gz-cmake/blob/e9a97b1214b920b17983ab358e790f2dc631e8d7/cmake/GzPython.cmake#L15-L45) can be deprecated
    * [x] https://github.com/gazebosim/gz-math/pull/588
    * [x] https://github.com/gazebosim/gz-physics/pull/625
    * [x] https://github.com/gazebosim/gz-rendering/pull/990
* [x] https://github.com/gazebosim/gz-cmake/pull/431
* [ ] won't fix ~~[gz-config.cmake.in:86-88](https://github.com/gazebosim/gz-cmake/blob/e9a97b1214b920b17983ab358e790f2dc631e8d7/cmake/gz-config.cmake.in#L86-L88)~~
* [ ] FindSQLite3.cmake (see https://github.com/gazebosim/gz-cmake/issues/312#issuecomment-1262432843 and https://github.com/traversaro/gz-cmake/commit/a61bfc5eb246e5b2ae36bf31d7122fabcb87fb71)
* [x] In downstream packages with python bindings, there are checks for cmake version >= 3.12 like in [gz-math](https://github.com/gazebosim/gz-math/blob/main/src/python_pybind11/CMakeLists.txt#L76-L82)
    * [x] https://github.com/gazebosim/gz-math/pull/587
    * [x] https://github.com/gazebosim/sdformat/pull/1408
    * [x] https://github.com/gazebosim/gz-transport/pull/504
    * [x] https://github.com/gazebosim/gz-sim/pull/2420
* [x] Require cmake 3.22.1 in all Ionic packages
    * [x] gz-cmake4 https://github.com/gazebosim/gz-cmake/pull/396
    * [x] gz-utils3 https://github.com/gazebosim/gz-utils/pull/132
    * [x] gz-math8 https://github.com/gazebosim/gz-math/pull/587
    * [x] sdformat15 https://github.com/gazebosim/sdformat/pull/1408
    * [x] gz-plugin3 https://github.com/gazebosim/gz-plugin/pull/146
    * [x] gz-common6 https://github.com/gazebosim/gz-common/pull/619
    * [x] gz-rendering9 https://github.com/gazebosim/gz-rendering/pull/1037
    * [x] gz-physics8 https://github.com/gazebosim/gz-physics/pull/671
    * [x] gz-msgs11 https://github.com/gazebosim/gz-msgs/pull/444
    * [x] gz-transport13 https://github.com/gazebosim/gz-transport/pull/504
    * [x] gz-fuel-tools10 https://github.com/gazebosim/gz-fuel-tools/pull/436
    * [x] gz-gui9 https://github.com/gazebosim/gz-gui/pull/634
    * [x] gz-sensors9 https://github.com/gazebosim/gz-sensors/pull/457
    * [x] gz-sim9 https://github.com/gazebosim/gz-sim/pull/2420
    * [x] gz-launch8 https://github.com/gazebosim/gz-launch/pull/272

**Comment by scpeters** [comment]
For reference:

* [Ubuntu 20.04 includes cmake 3.16.3](https://packages.ubuntu.com/focal/cmake)
* [Ubuntu 22.04 includes cmake 3.22.1](https://packages.ubuntu.com/jammy/cmake)

**Comment by Bi0T1N** [comment]
A brief summary of additions can be found [here](https://cliutils.gitlab.io/modern-cmake/chapters/intro/newcmake.html). Simpler than checking all the [release notes](https://cmake.org/cmake/help/latest/release/index.html).

Here is an initial list:
- FindPython (CMake 3.12 but got enhancements in almost each new release)
- More support for generator expressions (CMake 3.16)
- ~~FindCUDAToolkit (CMake 3.17)~~ (maybe more important for downstream AI projects or if the waves in gz-rendering are ported from OpenGL Shading Language)
- Support for C++20 (CMake 3.12) and C++23 (CMake 3.20)
- Colored messages based on message type (CMake 3.21)

**Comment by scpeters** [comment]
since Harmonic has already dropped support for 20.04, I think we can target cmake 3.22.1 since that is in 22.04

**Comment by scpeters** [comment]
bumping the required cmake version in `gz-cmake4` to 3.22.1 in https://github.com/gazebosim/gz-cmake/pull/396

we can start using new features in follow-up pull requests

**Comment by scpeters** [comment]
having worked with some of the `find_package(Python3)` logic, I think we should just deprecate `GzPython`

**Comment by mjcarroll** [comment]
Just a note that `cmake_path` can be used for path manipulation in 3.20+ and may tidy up code: https://cmake.org/cmake/help/latest/command/cmake_path.html

**Comment by scpeters** [comment]
If we decide not to support Ubuntu 22.04 with Ionic, we could increase the required cmake version to 3.28.3:

* https://packages.ubuntu.com/noble/cmake

**Comment by scpeters** [comment]
I just noticed from [What's new in cmake](https://cliutils.gitlab.io/modern-cmake/chapters/intro/newcmake.html) that the `create_symlink` command can now be used on Windows as of version 3.13:

* https://cmake.org/cmake/help/latest/release/3.13.html#command-line
