### ISSUE TITLE
cppcheck needs to be updated to use c++17

### ISSUE THREAD

**Issue by azeey** [gazebosim/gz-cmake#378]
The version of `cppcheck` in Focal and later supports `c++17`, so we should update it.
https://github.com/gazebosim/gz-cmake/blob/87c2a5429d89987816059411d4dec8c0b3369ebd/cmake/GzCodeCheck.cmake#L20

**Comment by Bi0T1N** [comment]
Also consider the [`<LANG>_CPPCHECK`](https://cmake.org/cmake/help/latest/prop_tgt/LANG_CPPCHECK.html#prop_tgt:%3CLANG%3E_CPPCHECK) property of CMake 3.10 and newer. Example can be found [here](https://stackoverflow.com/questions/48625499/cppcheck-support-in-cmake).
