### ISSUE TITLE
`EXTRA_ARGS` should be a multi-value arg

### ISSUE THREAD

**Issue by dg0yt** [gazebosim/gz-cmake#391]
## Environment
* OS Version: Ubuntu 20.04
* Source, vcpkg, version 3.4.1

## Description

`EXTRA_ARGS` for `gz_find_package` should be pass forward to `find_package`.
https://github.com/gazebosim/gz-cmake/blob/200de1b26edbad9ad1d7efd7c29dd4f2080edefa/cmake/GzFindPackage.cmake#L112
https://github.com/gazebosim/gz-cmake/blob/200de1b26edbad9ad1d7efd7c29dd4f2080edefa/cmake/GzFindPackage.cmake#L209-L211

However, only the first argument is actually passed on. Any other argument is interpreted separately, so the desired effect cannot be achieved.

# Steps to reproduce

This should pass additional `NAMES tinyxml2-expected` to `find_package`.

~~~cmake
gz_find_package(TINYXML2 PRETTY tinyxml2
     EXTRA_ARGS NAMES tinyxml2-expected
     REQUIRED_BY graphics
     PRIVATE_FOR graphics)
~~~

# Output 
~~~
CMake Warning (dev) at /vcpkg/installed/x64-linux/share/cmake/gz-cmake3/cmake3/GzUtils.cmake:313 (message):
  

  The build script has specified some unrecognized arguments for
  gz_find_package(~):

  tinyxml2-expected

  Either the script has a typo, or it is using an unexpected version of
  gz-cmake.  The version of gz-cmake currently being used is 3.4.1

Call Stack (most recent call first):
  /vcpkg/installed/x64-linux/share/cmake/gz-cmake3/cmake3/GzFindPackage.cmake:178 (_gz_cmake_parse_arguments)
  CMakeLists.txt:63 (gz_find_package)
~~~
`tinyxml2-expected` is parsed as a separate arg to `gz_find_package`.
## 

# Suggestion

`EXTRA_ARGS` should be moved to the multi-option args in these spots:
https://github.com/gazebosim/gz-cmake/blob/200de1b26edbad9ad1d7efd7c29dd4f2080edefa/cmake/GzFindPackage.cmake#L158-L159
https://github.com/gazebosim/gz-cmake/blob/200de1b26edbad9ad1d7efd7c29dd4f2080edefa/cmake/GzFindPackage.cmake#L173-L174

**Comment by j-rivero** [comment]
Thanks Kai for issue! Would you mind sending a PR to fix it against the branch you are interested into? I'll take care of reviewing and back/forward porting.

**Comment by dg0yt** [comment]
I won't send a PR. The actual changes I needed/did for the vcpkg port moved into a different direction: patch the Find modules, so that we don't have to patch each consumer there.
(There are two other changes which are suitable for upstreaming: 
https://github.com/microsoft/vcpkg/blob/06c79a9afa6f99f02f44d20df9e0848b2a56bf1b/ports/gz-cmake3/dependencies.patch#L93-L110
But I still to find the time to do that.)
