### ISSUE TITLE
Question for ignition-cmake2 version

### ISSUE THREAD

**Issue by bchoineubility** [gazebosim/gz-cmake#411]
Hi,

I am new comer for ignition-cmake2 system not familiar with it.  I have tried to build ignition packages and have encounter ignition-cmake2 version using in the ignition packages are different and they are using `REQUIRED` directive with specifying version. 

I think if my ignition-cmake2 version is higher than them, it will not be problem to build those packages. 

I hope to know it is correct or not.

BR,
Mark

**Comment by scpeters** [comment]
yes, it should build correctly with a newer version of ignition-cmake2

If you're using `ignition-cmake2`, I'm guessing you're using Fortress or Citadel, and I recommend the following installation instructions:

* https://gazebosim.org/docs/fortress/install_ubuntu_src
* https://gazebosim.org/docs/citadel/install_ubuntu_src

also, for installation questions, I recommend https://robotics.stackexchange.com

**Comment by bchoineubility** [comment]
Hi @scpeters 

Thanks for kind reply.

I will ask questions at https://robotics.stackexchange.com from now on. 

BR,
Mark
