### ISSUE TITLE
Missing some windows compiler warnings?

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-cmake#42]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/issues/42)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
While using the `gz11` branch of ign-math, I had to update our fork of gtest to fix some windows build failures:

* https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/pull-requests/271/gcc8-use-new-version-of-gtest-to-fix/diff

Today I just noticed that the `ign-math2` and `ign-math3` branches have loads of compiler warnings related to `std::tr1` stuff in gtest, which was the cause of the failure in `gz11`:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_math-ci-ign-math2-windows7-amd64&build=9)](https://build.osrfoundation.org/job/ignition_math-ci-ign-math2-windows7-amd64/9/) https://build.osrfoundation.org/view/os_windows/job/ignition_math-ci-ign-math2-windows7-amd64/9/warnings43Result/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_math-ci-ign-math3-windows7-amd64&build=10)](https://build.osrfoundation.org/job/ignition_math-ci-ign-math3-windows7-amd64/10/) https://build.osrfoundation.org/view/os_windows/job/ignition_math-ci-ign-math3-windows7-amd64/10/warnings43Result/

Oddly, the `ign-math4` build does not report any warnings:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_math-ci-ign-math4-windows7-amd64&build=24)](https://build.osrfoundation.org/job/ignition_math-ci-ign-math4-windows7-amd64/24/) https://build.osrfoundation.org/job/ignition_math-ci-ign-math4-windows7-amd64/24/warnings43Result/

The `ign-math2` and `ign-math3` branches have slightly different versions of gtest, but `ign-math4` has the same version as `ign-math3`, so I would expect it to have the same compiler warnings. Also, I've reported this here because `ign-math4` uses `ign-cmake0`, while math2/3 have their own cmake code.

Any ideas @mxgrey ?

**Comment by azeey** [comment]
Closing since the mentioned packages are all EOL.
