### ISSUE TITLE
ign-cmake gz11 BUILD_TESTING still fails to build...

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-cmake#52]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/issues/52)) by Pei JIA (Bitbucket: [jiapei100](https://bitbucket.org/%7B18260a78-aa91-4162-bcbb-4faf42e302fb%7D/)).**

----------------------------------------
Bug Report Template
Copy, paste, and then fill-out this template in the description field to submit a bug report.

# Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the Q&A board for common solutions: http://answers.gazebosim.org
    * Checked that your issue isn't already filed.
    * Checked that there is not already an Ignition package that provides the described functionality: https://ignitionrobotics.org/libs

# Description 

```console
[ 34%] Performing test step for 'component_deps_Release'
cd ....../ign-cmake/build/examples/component_deps_Release-prefix/src/component_deps_Release-build && /usr/local/bin/cmake -E copy ....../ign-cmake/build/examples/component_deps_Release_pass.xml ....../ign-cmake/build/examples/test_results/component_deps_Release.xml
cd ....../ign-cmake/build/examples/component_deps_Release-prefix/src/component_deps_Release-build && /usr/local/bin/cmake -E touch ....../ign-cmake/build/examples/component_deps_Release-prefix/src/component_deps_Release-stamp/component_deps_Release-test
[ 34%] Completed 'component_deps_Release'
cd ....../ign-cmake/build/examples && /usr/local/bin/cmake -E make_directory ....../ign-cmake/build/examples/CMakeFiles
cd ....../ign-cmake/build/examples && /usr/local/bin/cmake -E touch ....../ign-cmake/build/examples/CMakeFiles/component_deps_Release-complete
cd ....../ign-cmake/build/examples && /usr/local/bin/cmake -E touch ....../ign-cmake/build/examples/component_deps_Release-prefix/src/component_deps_Release-stamp/component_deps_Release-done
make[2]: Leaving directory '....../ign-cmake/build'
[ 34%] Built target component_deps_Release
make[1]: Leaving directory '....../ign-cmake/build'
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
```

# Steps to Reproduce

1. checkout **gz11** branch, and try to **compile/build** it, with **BUILD_TESTING** turned **ON**.
2. make
3. got the above **ERROR** message.

**Expected behavior:**  

Build through

**Actual behavior:**

Failed with the above **ERROR** messages.

**Reproduces how often:** 

Always

# Versions

```console
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
➜  ~ gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

# Additional Information

I've already enabled **-std=c++17**

Cheers
Pei

**Comment by azeey** [comment]
Closing since there hasn't been any activity.
