### ISSUE TITLE
Support images on tutorials generated with `make doc`

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-cmake#54]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/issues/54)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
# Summary

When running `make doc`, markdown tutorials under the `tutorials` folder are turned into HTML under the `doxygen/html` folder. It would be nice to also copy images from that directory so that they can be uploaded together with the generated HTML to the same server.

# Motivation

Using images in tutorials is very important.

# Describe alternatives you've considered

It's already possible to use HTML directly in tutorials and pass full URLs that point to other sites. However, this means that the generated documentation is not self-contained.

**Comment by chapulina** [comment]
This is already supported by using doxygen's `@image`. All the library needs to do is a CMake command like [this](https://github.com/ignitionrobotics/ign-rendering/blob/2c85d92f34f29e997aaf6b085ea376412032e5eb/CMakeLists.txt#L160) to copy the images to the doxygen folder:

`file(COPY ${CMAKE_SOURCE_DIR}/tutorials/img/ DESTINATION ${CMAKE_BINARY_DIR}/doxygen/html/img/)`

We could consider adding this line to `ign_create_docs`, or just keep adding it to each library as needed.

**Comment by azeey** [comment]
The `@image` or `\image` tag now works with the fix in https://github.com/gazebosim/gz-cmake/pull/183.
