### ISSUE TITLE
Provide check_test_ran.py script

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-cmake#58]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/issues/58)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
Currently the ignition packages all have their own check_test_ran.py script, and they have diverged somewhat, with some packages showing tests that fail to run as `Results.test_ran` instead of giving the name of the failing test. This was originally fixed in [gazebo pull request 413](https://bitbucket.org/osrf/gazebo/pull-requests/413/display-name-of-tests-that-dont-run-in/diff) but not propagated. We should consider installing a fixed version of the `check_test_ran.py` script from ign-cmake.

I am patching some individual scripts now as needed:

* https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-sensors/pull-requests/50/show-name-for-tests-that-failed-to-run/diff

**Comment by azeey** [comment]
This seems to be fixed since the file exists in gz-cmake now: https://github.com/gazebosim/gz-cmake/blob/200de1b26edbad9ad1d7efd7c29dd4f2080edefa/tools/check_test_ran.py
