### ISSUE TITLE
package.xml for easy integration with catkin/ament

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-cmake#68]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/issues/68)) by Kunal Tyagi (Bitbucket: [kunaltyagi](https://bitbucket.org/%7B549058f2-c154-4c9c-a8ac-be524224888a%7D/)).**

----------------------------------------
Hi

I noticed that none of ignition's repositories (and gazebo) have a package.xml which makes creating a from source setup a bit of a nuisance. Is there a rationale behind this (except that 
ROS and ignition are independent)?
 
 I've created `package.xml` for my own use for gazebo, ign-math, ign-cmake, ign-tools, ign-msgs, ign-transport and meta-package ignition (following the traditional layout in ROS). If you're interested, I can upstream them.

**Comment by scpeters** [comment]
`package.xml` files have been added to harmonic and ionic as part of https://github.com/gazebo-tooling/release-tools/issues/1117
