### ISSUE TITLE
Private dependencies of core library treated as public in pkg-config files

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-cmake#72]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/issues/72)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
# Summary

Dependencies of a core library that are marked as `PRIVATE` in the `ign_find_package` and `target_link_libraries` calls are not being marked as Requires.private in the generated pkg-config `.pc` files; instead they are included as public `Requires` dependencies. By contrast, dependencies of components marked as `PRIVATE_FOR` in `ign_find_package` and `PRIVATE` in `target_link_libraries` are properly included in the generated `.pc` files.

# Motivation

It's useful to be able to mark dependencies as `PRIVATE` if they aren't exposed in the public API. For example, [ign-fuel-tools uses CURL as a private dependency](https://github.com/ignitionrobotics/ign-fuel-tools/blob/0620e7591dbed96ff4a94b5a71b720ae65eb9efb/CMakeLists.txt#L33), but it is being exported as a public dependency, which has been causing a problem on macOS since homebrew recently disabled a `libcurl.pc` file (for complicated reasons), which is causing some bottle builds to fail:

* https://github.com/osrf/homebrew-simulation/pull/995#issuecomment-610276166

ign-fuel-tools shouldn't even need to find that `libcurl.pc` file, but I guess that has exposed this issue, which we didn't realize.

I've also created an example test in fe27cfd8912ec8b6ad60747c1ee7d28feb145d3a that illustrates the problem.

# Describe alternatives you've considered

I think it's a bug we should fix.

# Additional context

**Comment by scpeters** [comment]
fixed in [bitbucket pr #184](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/pull-requests/184)
